removed support for .ts files in mod
slackapi/deno-slack-runtime pull request #20
Opened 2022-07-11 23:45 UTC by jmplexi

###  Summary

Removed support for .ts files in the mod.ts file.

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/{project_slug}/blob/main/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

2022-07-12 12:11 UTC, filmaj requested changes
Left a couple of comments. Let's please also make sure to write tests for the `dispatch-payload.ts` module while we're here, since those seem to be missing.

2022-07-12 12:11 UTC, filmaj commented on src/mod.ts
> +    const supportedExts = ["js"];
If we don't expect to support multiple different filetypes anymore, then let's remove most of the code here: no point having an array of extensions, or looping over them, to return an array of files.

2022-07-14 22:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slackapi/deno-slack-runtime?pullRequest=20) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/slackapi/deno-slack-runtime?pullRequest=20) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jmplexi<br/>:x: user.email<br/><hr/>**user.email** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slackapi/deno-slack-runtime?pullRequest=20) it.</sub>

2022-07-22 00:32 UTC, shapirone requested changes
looks like we accidentally dropped the extension

2022-07-22 00:32 UTC, shapirone commented on src/mod.ts
> +    return [`${functionDir}/${functionCallbackId}`];
We need to keep the `js` extension here on the end

2022-07-30 00:00 UTC, selfcontained approved these changes
Nice, thanks for the tests too!

2022-07-30 00:00 UTC, merged